grafana:
  adminPassword: grafanainvast
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: "nginx",
      ingress.kubernetes.io/rewrite-target: "/"
    }
    hosts:
    - "aa2e920848cd54b74b7b49ac188afab2-883849872.ap-northeast-1.elb.amazonaws.com"
    path: "/grafana"
  grafana.ini: 
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {
      ingress.kubernetes.io/rewrite-target: "/"
    }
    hosts:
    - "aa2e920848cd54b74b7b49ac188afab2-883849872.ap-northeast-1.elb.amazonaws.com"
    paths:
    - "/prometheus"
  prometheusSpec:
    routePrefix: "/prometheus"
    additionalScrapeConfigs:
      - job_name: airflow-statsd-exporter
        static_configs:
          - targets: ['airflow-statsd.airflow:9102']
alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {
      ingress.kubernetes.io/rewrite-target: "/"
    }
    hosts:
    - "aa2e920848cd54b74b7b49ac188afab2-883849872.ap-northeast-1.elb.amazonaws.com"
    paths:
    - "/alertmanager"
  alertmanagerSpec:
    routePrefix: "/alertmanager"
